### ISSUE TITLE
mySIMBL causes massive system studdering

### ISSUE THREAD

**Issue by chase9** [w0lfschild/mySIMBL#72] opened 2018-02-05 23:06 UTC
OS: macOS 10.13.4 Beta (17E139)
Model: MacBookPro11,3

I was having problems with my system becoming extremely slow, especially for a while after I would open applications. Eventually narrowed it down to mySIMBL. Uninstalling made all the slowdowns go away.

I would notice activity monitor showing larger than usual CPU usage from spindump and tailspind. I can't remember this happening before on macOS beta (I only reinstalled mySIMBL recently before upgrading) so I'm wondering if this is a conflict between the enhanced diagnostics of macOS beta and mySIMBL?

Also to note that none of my plugins were working, although mySIMBL reported green across the board. I had reenabled SIP and I notice other issues about this, so perhaps unrelated.

**Comment by w0lfschild** [comment] 2018-05-06 16:25
I've noticed these process hang as well. Force closing them works fine but I wonder what the root cause is.

Maybe mySIMBL is trying to load into them? I'll look into it.

**Closed** 2019-12-15 06:55 UTC
Labels: bug
